---
- hosts: 127.0.0.1
  connection: local
  vars:
    app_key: Micro Linux Node Keys
    ec2_instance_type: t2.micro
    amazon_ami: ami-0cf14ae9dd391449a
    ec2_aws_region: us-east-2
    vpc_submit_id: subnet-90cf9eea
  tasks:
    - name: create a new ec2 instance
      ec2:
        aws_access_key: "{{ ansible_facts['env']['AWS_ACCESS_KEY'] }}"
        aws_secret_key: "{{ ansible_facts['env']['AWS_SECRET_KEY'] }}"
        key_name: "{{ app_key }}"
        group: webserver
        instance_type: "{{ ec2_instance_type }}"
        region: "{{ ec2_aws_region }}"
        image: "{{ amazon_ami }}"
        wait: yes
        wait_timeout: 500
        volumes:
          - device_name: /dev/xvda
            volume_size: 8
            volume_type: gp2
            delete_on_termination: true
        vpc_subnet_id: "{{ vpc_submit_id }}"
        assign_public_ip: yes
      register: ec2
